In [1]:
import tensorflow as tf 

In [3]:
mnist = tf.keras.datasets.mnist
(train_X,train_y),(test_X,test_y)=mnist.load_data()
train_X,test_X=train_X/255.0,test_X/255.0

In [6]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(train_X[:1]).numpy()
predictions

array([[ 0.34220988,  0.62175155,  0.53517705,  0.42806536, -0.2647493 ,
         0.19705717, -0.08416718, -0.33412164, -0.21646732,  0.7475097 ]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.1078984 , 0.14269817, 0.13086382, 0.11757137, 0.05880523,
        0.09332027, 0.07044365, 0.05486406, 0.06171413, 0.16182086]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(train_y[:1],predictions).numpy()

2.371718

In [17]:
model.compile(optimizer='adam',
        loss=loss_fn,
        metrics=['accuracy'])

In [18]:
model.fit(train_X,train_y,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 825us/step - loss: 0.2900 - accuracy: 0.9164
Epoch 2/5
1875/1875 [==============================] - 2s 841us/step - loss: 0.1395 - accuracy: 0.9588
Epoch 3/5
1875/1875 [==============================] - 2s 857us/step - loss: 0.1074 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 1s 777us/step - loss: 0.0857 - accuracy: 0.9739
Epoch 5/5
1875/1875 [==============================] - 2s 838us/step - loss: 0.0731 - accuracy: 0.9771


&lt;tensorflow.python.keras.callbacks.History at 0x15b534f50&gt;

In [19]:
model.evaluate(test_X,test_y,verbose=2)

313/313 - 0s - loss: 0.0757 - accuracy: 0.9745


[0.07570958137512207, 0.9745000004768372]

In [20]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [21]:
probability_model(test_X[:5])

&lt;tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.90731328e-07, 2.83464208e-09, 2.34748018e-06, 9.92692585e-05,
        6.82136708e-11, 2.97247368e-07, 9.46647491e-13, 9.99895692e-01,
        1.19929638e-07, 1.98946282e-06],
       [8.56397508e-10, 6.23701226e-06, 9.99986529e-01, 4.85551891e-06,
        2.55131694e-14, 6.06402068e-07, 4.24911040e-09, 4.29989194e-14,
        1.83055408e-06, 2.50797104e-14],
       [9.03953242e-06, 9.98957157e-01, 1.54538051e-04, 1.64790908e-05,
        1.98407961e-05, 2.54829752e-06, 2.23010557e-05, 3.99312150e-04,
        4.18418087e-04, 3.13493302e-07],
       [9.99994516e-01, 6.21833784e-09, 1.72483226e-06, 1.07933595e-07,
        4.92982721e-09, 8.10889986e-08, 1.60697084e-06, 1.24224937e-06,
        1.74832149e-09, 7.34625530e-07],
       [1.08078502e-05, 3.85468297e-08, 2.29046727e-05, 5.94310769e-08,
        9.97297227e-01, 4.84125337e-07, 1.14384409e-06, 1.13441347e-04,
        3.88639637e-05, 2.51502497e-03]], dtype=float32)&gt;